// DESCRIPTION: Generated by verilator_includer via makefile
#define VL_INCLUDE_OPT include
#include "Varchitecture_components.cpp"
#include "Varchitecture_components___024root__0.cpp"
#include "Varchitecture_components__main.cpp"
#include "Varchitecture_components__Trace__0.cpp"
#include "Varchitecture_components___024root__Slow.cpp"
#include "Varchitecture_components___024root__0__Slow.cpp"
#include "Varchitecture_components__Syms__Slow.cpp"
#include "Varchitecture_components__Trace__0__Slow.cpp"
#include "Varchitecture_components__TraceDecls__0__Slow.cpp"
